export enum screenNames {
  BOTTOMTABS = 'BOTTOMTABS',
  HOME = 'HOME',
  PRODUCTDETAILS = 'PRODUCTDETAILS',
  SHOPPINGCART = 'SHOPPINGCART',
  CATEGORYTAB = 'CATEGORYTAB',
  FAVORITETAB = 'FAVORITETAB',
  MORETAB = 'MORETAB',
}
