export enum screenNames {
  BOTTOMTABS = 'BOTTOMTABS',
  HOME = 'HOME',
  PRODUCTDETAILS = 'PRODUCTDETAILS',
  SHOPPINGCARD = 'SHOPPINGCARD',
  CATEGORYTAB = 'CATEGORYTAB',
  FAVORITETAB = 'FAVORITETAB',
  MORETAB = 'MORETAB',
}
